[package]
name = "serlo_he_spec_meta"
version = "0.1.0"
authors = ["Valentin Roland <valentin@vroland.de>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["serde", "v5"] }
serde = "1.0"
serde_derive = "1.0"
